Hungarian/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hungarian.Data;
using Hungarian.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hungarian.Controllers
{
    public class FeedbacksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FeedbacksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Feedbacks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Feedback.ToListAsync());
        }

        // GET: Feedbacks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedback
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }
        [Authorize]
        // GET: Feedbacks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Feedbacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Contact,Message")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedback);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(feedback);
        }
        [Authorize(Policy = "Private")]
        // GET: Feedbacks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedback.FindAsync(id);
            if (feedback == null)
            {
                return NotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Contact,Message")] Feedback feedback)
        {
            if (id != feedback.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feedback);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackExists(feedback.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(feedback);
        }
        [Authorize(Policy = "Private")]
        // GET: Feedbacks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedback
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feedback = await _context.Feedback.FindAsync(id);
            _context.Feedback.Remove(feedback);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedbackExists(int id)
        {
            return _context.Feedback.Any(e => e.Id == id);
        }
    }
}

Hungarian/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hungarian.Data;
using Hungarian.Models;
using Hungarian.Interfaces;
using Hungarian.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Hungarian.Controllers
{

    public class MenuController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMenuRepository _menuRepository;
        private readonly ICategoryRepository _categoryRepository;
        public MenuController(ApplicationDbContext context, IMenuRepository menuRepository, ICategoryRepository categoryRepository)
        {
            _menuRepository = menuRepository;
            _categoryRepository = categoryRepository;
            _context = context;
        }
        [Authorize(Policy= "Private")]
        // GET: Menu
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Menus.Include(m => m.Category);
            return View(await applicationDbContext.ToListAsync());
        }
        public ViewResult Details(int menuId)
        {
            var menu = _menuRepository.Menus.FirstOrDefault(d => d.MenuId == menuId);
            if (menu == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(menu);
        }
        //// GET: Menu/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var menu = await _context.Menus
        //        .Include(m => m.Category)
        //        .FirstOrDefaultAsync(m => m.MenuId == id);
        //    if (menu == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(menu);
        //}
        [Authorize(Policy = "Admin")]
        // GET: Menu/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId");
            return View();
        }

        // POST: Menu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MenuId,Name,ShortDescription,LongDescription,Price,ImageUrl,ImageThumbnailUrl,IsPreferredMenu,InStock,CategoryId")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", menu.CategoryId);
            return View(menu);
        }
        //
        [Authorize(Policy = "Admin")]
        // GET: Menu/Edit/5
        public async Task<IActionResult> Edit(int? menuId)
        {
            if (menuId == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(menuId);
            if (menu == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", menu.CategoryId);
            return View(menu);
        }

        // POST: Menu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int menuId, [Bind("MenuId,Name,ShortDescription,LongDescription,Price,ImageUrl,ImageThumbnailUrl,IsPreferredMenu,InStock,CategoryId")] Menu menu)
        {
            if (menuId != menu.MenuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.MenuId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", menu.CategoryId);
            return View(menu);
        }
        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Menu> menus;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                menus = _menuRepository.Menus.OrderBy(p => p.MenuId);
            }
            else
            {
                menus = _menuRepository.Menus.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Menu/List.cshtml", new MenuListViewModel { Menus = menus, CurrentCategory = "All dishes" });
        }
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Menu> menus;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                menus = _menuRepository.Menus.OrderBy(p => p.MenuId);
                currentCategory = "All dishes";
            }
            else
            {
                if (string.Equals("Snacks", _category, StringComparison.OrdinalIgnoreCase))
                    menus = _menuRepository.Menus.Where(p => p.Category.CategoryName.Equals("Snacks")).OrderBy(p => p.Name);
                else
                    menus = _menuRepository.Menus.Where(p => p.Category.CategoryName.Equals("Main Course")).OrderBy(p => p.Name);

                currentCategory = _category;
            }

            return View(new MenuListViewModel
            {
                Menus = menus,
                CurrentCategory = currentCategory
            });
        }
        [Authorize(Policy = "Private")]
        // GET: Menu/Delete/5
        public async Task<IActionResult> Delete(int? menuId)
        {
            if (menuId == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .Include(m => m.Category)
                .FirstOrDefaultAsync(m => m.MenuId == menuId);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Menu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int menuId)
        {
            var menu = await _context.Menus.FindAsync(menuId);
            _context.Menus.Remove(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int menuId)
        {
            return _context.Menus.Any(e => e.MenuId == menuId);
        }
    }
}

Hungarian/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hungarian.Interfaces;
using Hungarian.Models.Dishes;
using Hungarian.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hungarian.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IMenuRepository _menuRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IMenuRepository menuRepository, ShoppingCart shoppingCart)
        {
            _menuRepository = menuRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        [Authorize]
        public RedirectToActionResult AddToShoppingCart(int menuId)
        {
            var selectedMenu = _menuRepository.Menus.FirstOrDefault(p => p.MenuId == menuId);
            if (selectedMenu != null)
            {
                _shoppingCart.AddToCart(selectedMenu, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int menuId)
        {
            var selectedMenu = _menuRepository.Menus.FirstOrDefault(p => p.MenuId == menuId);
            if (selectedMenu != null)
            {
                _shoppingCart.RemoveFromCart(selectedMenu);
            }
            return RedirectToAction("Index");
        }

    }
}

Hungarian/Views/Shared/Footer_PartialView.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>

    <script type="text/javascript" language="javascript">
        function GetDateTime() {
            var param1 = new Date();
            var param2 = new Date();
            var param3 = param1.getDate() + '/' + (param1.getMonth() + 1) + '/' + param1.getFullYear();
            var param4 = param2.getHours() + ':' + param2.getMinutes() + ':' + param2.getSeconds();
            document.getElementById('date').innerHTML = param3;
            document.getElementById('time').innerHTML = param4;

        }
    </script>
</head>
<body onload="GetDateTime()">
    <form id="form1" runat="server">
        <p>
            Date : <span id="date"></span>
            Time : <span id="time"></span>
        </p>
    </form>
</body>
</html>

Hungarian/Views/Shared/MenuOverviewSummary.cshtml
@model Menu

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Menu" asp-action="Details" asp-route-id="@Model.MenuId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success " id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-pieId="@Model.MenuId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

Hungarian/Views/Shared/MenusSummary.cshtml
@model Menu

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" class="rounded mx-auto d-block" style="width:300px;height:244px;" alt="" />
        
        <div class="caption text-center">
            <h3>@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Menu" asp-action="Details" asp-route-menuId="@Model.MenuId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-center">
            <p class="button">
                <a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-menuId="@Model.MenuId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

Hungarian/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hungarian</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3" style="height: 55px;" >
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/hungWithScooty.png" style="height:30px;width:auto" />
                </a>
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hungarian</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1" style="padding-top: 1%;" >
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li>
                <a class="nav-link text-light" asp-area="" asp-controller="FoodMangs" asp-action="Index">Menu</a>
        </li>*@
                       @await Component.InvokeAsync("CategoryMenu")
                        @*<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" style="color:white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-area="" asp-controller="FoodMangs" asp-action="ItemsDisplay">Chinese</a>
                    <a class="dropdown-item" asp-area="" asp-controller="FoodMangs" asp-action="ItemsDisplay">Italian</a>
                                 <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
        </div>
                                </li>*@
                        <li>
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Feedbacks" asp-action="Index">Feedback</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                          @await Component.InvokeAsync("ShoppingCartSummary")
                    <li>
                        <form class="navbar-form" asp-controller="Menu" asp-action="Search" method="get">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search for a dish" name="searchString" value="@ViewData["searchString"]" style="background-color: white;
                                                background-image: url(https://www.w3schools.com/css/searchicon.png);
                                                background-position: 10px 7px;
                                                background-repeat: no-repeat;
                                                padding-left: 40px;
                                            ">
                            </div>
                        </form>
                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="text-right"><div class="float-left"><img src="~/Images/hungarianLogo.png" style="height:70px;width:auto;" /></div><partial name="Footer_PartialView" /></div>
        </div>
    </footer>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                <div class="text-right"><div class="float-left"><img src="~/Images/hungarianLogo.png" style="height:70px;width:auto;" /></div> &copy; 2020 - RollLogin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></div>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>